# Generated by Django 3.0.3 on 2020-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20200505_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
