# Generated by Django 3.0.3 on 2020-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_choice_is_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='to fill non-nullable field', max_length=200),
            preserve_default=False,
        ),
    ]
