# Generated by Django 3.0.3 on 2020-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
