# Generated by Django 3.0.6 on 2020-05-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_answer_choice_question_quiz_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='author',
        ),
        migrations.RemoveField(
            model_name='response',
            name='taken_by',
        ),
        migrations.RemoveField(
            model_name='response',
            name='test',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
