# Generated by Django 3.0.6 on 2020-05-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='groups',
            new_name='group',
        ),
    ]
