# Generated by Django 3.0.3 on 2020-05-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20200515_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='short_ans',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
