# Generated by Django 3.0.3 on 2020-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_question_maximum_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
