# Generated by Django 3.0.3 on 2020-06-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20200609_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
