# Generated by Django 3.0.3 on 2020-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_quiz_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='plag',
            field=models.BooleanField(default=False),
        ),
    ]
