# Generated by Django 3.0.3 on 2020-06-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_response_plag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='short_ans',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
